### ISSUE TITLE
农历闰月怎么转公历

### ISSUE THREAD

**Issue by NKnife** [yize/solarlunar#13]
> (Object)solarLunar.lunar2solar : 输入的日子为农历年月日
> 参数 : (Number)年,(Number)月,(Number)日

似乎没有传递是否闰月的参数

**Comment by flytrap** [comment]
* @param y  lunar year
   * @param m lunar month
   * @param d  lunar day
   * @param isLeapMonth  lunar month is leap or not.
还有一个参数，就是标识是否是闰月的，文档没写
