### ISSUE TITLE
数据源有错

### ISSUE THREAD

**Issue by NxGreen** [yize/solarlunar#6]
solarlunar/const/lunarInfo.js
本来上午只发现了96年的一个月份有错，提交后，最后找到了一份 百度万年历的数据源
https://www.baidu.com/cache/aladdin/ui/lunar7/lunar7.js?v=20170208
对比发现下三个有问题，并参照 香港天文台 数据源对比后，都已修改正确。

// 农历 1996 年 0x055c0 => 0x05ac0
香港天文台 数据源：http://www.weather.gov.hk/gts/time/calendar/text/T1996c.txt
原：0x055c0 => ‭0101 0101 1100 0000‬  五六七八月存在问题
改：0x05ac0 => ‭0101 1010 1100 0000‬

// 农历 2060 年 0x0a2e0 => 0x092e0
香港天文台 数据源：http://www.weather.gov.hk/gts/time/calendar/text/T2060c.txt
原：0x0a2e0 => ‭1010 0010 1110 0000‬  四月
改：0x092e0 => ‭1001 0010 1110 0000‬

// 农历 2097 年 0x0a2d0 => 0x0a4d0
香港天文台 数据源：http://www.weather.gov.hk/gts/time/calendar/text/T2098c.txt
原：0x0a2d0 => ‭1010 0010 1110 0000‬ 十一十二月
改：0x0a4d0 => 1010 0010 1101 0000

**Comment by yize** [comment]
赞，求 PR
