### ISSUE TITLE
2017年的数据源可能有误

### ISSUE THREAD

**Issue by jiawei686** [yize/solarlunar#8]
![image](https://user-images.githubusercontent.com/12953093/50080559-5ab06300-0227-11e9-94b6-7a9ec1d0e98c.png)
2017年12月14号转换后的结果是闰十月，不过查了一下好像最近一次闰十月是在1984年，下一次会在2166年。看了下这块的代码`leapMonth`函数应该没有问题，测试了下1984年的闰十月也可以正常得到判断。
对阴阳历转换不太懂，但是感觉数据源的2017年可能会有点问题，希望能够帮忙看下

**Comment by yize** [comment]
嗯，好像是不太对，我看下

**Comment by NxGreen** [comment]
刚才跟新到最新版本2.0.5 发现 闰月有问题。
公历1949.10.1号 不是闰月。但是 isLeap 显示的是true
![_20181222173447](https://user-images.githubusercontent.com/5018004/50372790-e5baa000-060f-11e9-92d5-cfb4ddf9541b.png)

**Comment by jiawei686** [comment]
> 嗯，好像是不太对，我看下
这回可以了，感谢！
